version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: gatsby build
          name: building
      - run: npm test -- --watch
          name: running tests
